# Generated by Django 3.2.7 on 2021-10-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('portsiya', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('prep', models.JSONField(default={'Cook': ' ', 'Prep': ' ', 'Yields': ' '})),
                ('image', models.ImageField(blank=True, upload_to='static/site/img')),
                ('steps', models.TextField()),
                ('Tayyorlash_uslubi_1', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_2', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_3', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_4', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_5', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_6', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_7', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_8', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_9', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_10', models.TextField(blank=True)),
                ('Tayyorlash_uslubi_11', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.SmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('ingredient', models.ManyToManyField(to='dashboard.Ingredients')),
            ],
        ),
    ]
