# Generated by Django 3.2.7 on 2021-10-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='usernmae',
            new_name='username',
        ),
    ]
