# Generated by Django 3.2.7 on 2021-10-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_chet_taomlar_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chet_taomlar',
        ),
    ]
